name: freqrise
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - attrs==24.2.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - h5py==3.12.1
      - idna==3.10
      - imageio==2.36.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==2.2.0
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.2.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - quantus==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - torch==2.5.1
      - torchmetrics==1.6.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - yarl==1.18.3
      - zennit==0.5.1
